"""Initial migration

Revision ID: 0937b98dad68
Revises: 
Create Date: 2025-11-09 00:39:57.864283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0937b98dad68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='강의 고유 ID'),
    sa.Column('category_type', sa.Enum('FRONTEND', 'BACKEND', 'DATA_ANALYSIS', 'AI', 'DESIGN', 'OTHER', name='categorytype'), nullable=False, comment='카테고리 유형'),
    sa.Column('course_type', sa.Enum('VOD', 'BOOST_COMMUNITY', 'KDC', name='coursetype'), nullable=False, comment='강의 유형'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='강의 제목'),
    sa.Column('description', sa.Text(), nullable=False, comment='강의 설명'),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=False, comment='썸네일 이미지 URL'),
    sa.Column('instructor_name', sa.String(length=100), nullable=False, comment='강사명'),
    sa.Column('instructor_bio', sa.Text(), nullable=False, comment='강사 소개'),
    sa.Column('instructor_image', sa.String(length=500), nullable=False, comment='강사 프로필 이미지 URL'),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficulty'), nullable=False, comment='난이도'),
    sa.Column('price_type', sa.Enum('FREE', 'PAID', 'NATIONAL_SUPPORT', name='pricetype'), nullable=False, comment='가격 유형'),
    sa.Column('price', sa.Integer(), nullable=False, comment='실제 가격 (원)'),
    sa.Column('total_duration', sa.Integer(), nullable=False, comment='전체 강의 시간 (초)'),
    sa.Column('faq', sa.Text(), nullable=True, comment='자주 묻는 질문 (JSON 형태)'),
    sa.Column('is_published', sa.Boolean(), nullable=False, comment='공개 여부'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_title'), 'courses', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='사용자 고유 ID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='비밀번호 해시 (소셜 로그인 시 NULL)'),
    sa.Column('nickname', sa.String(length=18), nullable=False, comment='닉네임 (2~18자)'),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False, comment='성별'),
    sa.Column('birth_date', sa.Date(), nullable=False, comment='생년월일'),
    sa.Column('profile_image', sa.String(length=500), nullable=True, comment='프로필 이미지 URL'),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', name='userrole'), nullable=False, comment='사용자 역할'),
    sa.Column('social_provider', sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', name='socialprovider'), nullable=False, comment='소셜 로그인 제공자'),
    sa.Column('social_id', sa.String(length=255), nullable=True, comment='소셜 로그인 고유 ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='계정 활성화 여부'),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False, comment='이메일 인증 여부'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='가입일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='마지막 로그인 일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='챕터 고유 ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='강의 ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='챕터 제목'),
    sa.Column('description', sa.Text(), nullable=True, comment='챕터 설명'),
    sa.Column('order_number', sa.Integer(), nullable=False, comment='챕터 순서'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_course_id'), 'chapters', ['course_id'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='쿠폰 고유 ID'),
    sa.Column('course_id', sa.Integer(), nullable=True, comment='강의 ID (NULL이면 전체 강의)'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='쿠폰 코드'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='쿠폰 이름'),
    sa.Column('description', sa.Text(), nullable=False, comment='쿠폰 설명'),
    sa.Column('discount_rate', sa.Integer(), nullable=True, comment='할인율 (%)'),
    sa.Column('discount_amount', sa.Integer(), nullable=True, comment='할인 금액 (원)'),
    sa.Column('valid_from', sa.DateTime(), nullable=False, comment='유효 시작일'),
    sa.Column('valid_until', sa.DateTime(), nullable=False, comment='유효 종료일'),
    sa.Column('max_usage', sa.Integer(), nullable=False, comment='최대 사용 인원 (0이면 무제한)'),
    sa.Column('used_count', sa.Integer(), nullable=False, comment='사용된 인원 수'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_table('course_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='질문 고유 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='작성자 ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='강의 ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='질문 제목'),
    sa.Column('content', sa.Text(), nullable=False, comment='질문 내용'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='조회수'),
    sa.Column('is_answered', sa.Boolean(), nullable=False, comment='답변 완료 여부'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='소프트 삭제 여부'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 일시'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='삭제한 사용자 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='작성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_questions_course_id'), 'course_questions', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_questions_user_id'), 'course_questions', ['user_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='수강 등록 고유 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='강의 ID'),
    sa.Column('enrolled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='등록일시'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='만료일시 (등록일 + 2년)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('progress_rate', sa.Float(), nullable=False, comment='전체 진행률 0~100'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='미션 고유 ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='강의 ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='미션 제목'),
    sa.Column('description', sa.Text(), nullable=False, comment='미션 설명'),
    sa.Column('mission_type', sa.Enum('MIDTERM', 'FINAL', name='missiontype'), nullable=False, comment='미션 유형'),
    sa.Column('question_type', sa.Enum('MULTIPLE_CHOICE', 'CODE', name='questiontype'), nullable=False, comment='문제 유형'),
    sa.Column('question_data', sa.JSON(), nullable=False, comment='문제 데이터 (JSON 형태)'),
    sa.Column('answer_data', sa.JSON(), nullable=False, comment='정답 데이터 (JSON 형태)'),
    sa.Column('max_score', sa.Integer(), nullable=False, comment='최대 점수'),
    sa.Column('passing_score', sa.Integer(), nullable=False, comment='통과 기준 점수'),
    sa.Column('max_attempts', sa.Integer(), nullable=False, comment='최대 제출 횟수'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_course_id'), 'missions', ['course_id'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='수료증 고유 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='강의 ID'),
    sa.Column('enrollment_id', sa.Integer(), nullable=False, comment='수강 등록 ID'),
    sa.Column('certificate_number', sa.String(length=100), nullable=False, comment='수료증 번호 (예: WNIV-2025-000001)'),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='발급일시'),
    sa.Column('pdf_url', sa.String(length=500), nullable=True, comment='PDF 파일 URL'),
    sa.Column('pdf_generated_at', sa.DateTime(), nullable=True, comment='PDF 생성일시'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_certificate_number'), 'certificates', ['certificate_number'], unique=True)
    op.create_index(op.f('ix_certificates_course_id'), 'certificates', ['course_id'], unique=False)
    op.create_index(op.f('ix_certificates_enrollment_id'), 'certificates', ['enrollment_id'], unique=True)
    op.create_index(op.f('ix_certificates_user_id'), 'certificates', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='댓글 고유 ID'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='질문 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='작성자 ID'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='부모 댓글 ID (대댓글용)'),
    sa.Column('content', sa.Text(), nullable=False, comment='댓글 내용'),
    sa.Column('is_instructor_answer', sa.Boolean(), nullable=False, comment='강사 답변 여부'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='소프트 삭제 여부'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제 일시'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='삭제한 사용자 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='작성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['course_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_question_id'), 'comments', ['question_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('lectures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='강의 영상 고유 ID'),
    sa.Column('chapter_id', sa.Integer(), nullable=False, comment='챕터 ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='강의 제목'),
    sa.Column('description', sa.Text(), nullable=True, comment='강의 설명'),
    sa.Column('video_url', sa.String(length=500), nullable=False, comment='동영상 URL'),
    sa.Column('video_type', sa.Enum('VOD', 'YOUTUBE', name='videotype'), nullable=False, comment='동영상 타입'),
    sa.Column('duration_seconds', sa.Integer(), nullable=False, comment='재생 시간 (초)'),
    sa.Column('order_number', sa.Integer(), nullable=False, comment='강의 순서'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lectures_chapter_id'), 'lectures', ['chapter_id'], unique=False)
    op.create_table('mission_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='제출 고유 ID'),
    sa.Column('mission_id', sa.Integer(), nullable=False, comment='미션 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('answer', sa.JSON(), nullable=False, comment='제출 답안 (JSON 형태)'),
    sa.Column('score', sa.Integer(), nullable=False, comment='획득 점수'),
    sa.Column('is_passed', sa.Boolean(), nullable=False, comment='통과 여부'),
    sa.Column('feedback', sa.Text(), nullable=True, comment='피드백'),
    sa.Column('execution_result', sa.JSON(), nullable=True, comment='실행 결과 (코드 제출형, JSON 형태)'),
    sa.Column('attempt_number', sa.Integer(), nullable=False, comment='시도 횟수'),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='제출일시'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_submissions_mission_id'), 'mission_submissions', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_submissions_user_id'), 'mission_submissions', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='결제 고유 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='강의 ID'),
    sa.Column('coupon_id', sa.Integer(), nullable=True, comment='쿠폰 ID'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='원래 가격'),
    sa.Column('discount_amount', sa.Integer(), nullable=False, comment='할인 금액'),
    sa.Column('final_amount', sa.Integer(), nullable=False, comment='최종 결제 금액'),
    sa.Column('payment_method', sa.Enum('CARD', 'TRANSFER', 'EASY', name='paymentmethod'), nullable=False, comment='결제 방식'),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False, comment='결제 상태'),
    sa.Column('transaction_id', sa.String(length=100), nullable=True, comment='PG사 거래 ID'),
    sa.Column('receipt_url', sa.String(length=500), nullable=True, comment='영수증 URL'),
    sa.Column('paid_at', sa.DateTime(), nullable=True, comment='실제 결제 완료 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_course_id'), 'payments', ['course_id'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('progresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='진행 상황 고유 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('lecture_id', sa.Integer(), nullable=False, comment='강의 ID'),
    sa.Column('watched_seconds', sa.Integer(), nullable=False, comment='총 시청 시간 (초)'),
    sa.Column('last_position', sa.Integer(), nullable=False, comment='마지막 시청 위치 (초)'),
    sa.Column('is_completed', sa.Boolean(), nullable=False, comment='완료 여부'),
    sa.Column('last_watched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='마지막 시청 일시'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='완료 일시'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progresses_lecture_id'), 'progresses', ['lecture_id'], unique=False)
    op.create_index(op.f('ix_progresses_user_id'), 'progresses', ['user_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='환불 고유 ID'),
    sa.Column('payment_id', sa.Integer(), nullable=False, comment='결제 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='환불 금액'),
    sa.Column('reason', sa.Text(), nullable=False, comment='환불 사유'),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='refundstatus'), nullable=False, comment='환불 상태'),
    sa.Column('admin_note', sa.Text(), nullable=True, comment='관리자 메모'),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='요청일시'),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='처리 완료 시각'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=True)
    op.create_index(op.f('ix_refunds_user_id'), 'refunds', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_user_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_progresses_user_id'), table_name='progresses')
    op.drop_index(op.f('ix_progresses_lecture_id'), table_name='progresses')
    op.drop_table('progresses')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_course_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_mission_submissions_user_id'), table_name='mission_submissions')
    op.drop_index(op.f('ix_mission_submissions_mission_id'), table_name='mission_submissions')
    op.drop_table('mission_submissions')
    op.drop_index(op.f('ix_lectures_chapter_id'), table_name='lectures')
    op.drop_table('lectures')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_question_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_certificates_user_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_enrollment_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_course_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_certificate_number'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_missions_course_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_course_questions_user_id'), table_name='course_questions')
    op.drop_index(op.f('ix_course_questions_course_id'), table_name='course_questions')
    op.drop_table('course_questions')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_chapters_course_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_courses_title'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
