"""delete some models and schemas

Revision ID: 297948e996b1
Revises: 595ed97f5cb8
Create Date: 2025-11-14 14:25:47.645314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '297948e996b1'
down_revision: Union[str, Sequence[str], None] = '595ed97f5cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mission_submissions_mission_id'), table_name='mission_submissions')
    op.drop_index(op.f('ix_mission_submissions_user_id'), table_name='mission_submissions')
    op.drop_table('mission_submissions')
    op.drop_index(op.f('ix_missions_course_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_certificates_certificate_number'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_course_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_enrollment_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_user_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_comments_question_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_course_questions_course_id'), table_name='course_questions')
    op.drop_index(op.f('ix_course_questions_user_id'), table_name='course_questions')
    op.drop_table('course_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_questions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('course_questions_id_seq'::regclass)"), autoincrement=True, nullable=False, comment='질문 고유 ID'),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='작성자 ID'),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='강의 ID'),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='질문 제목'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='질문 내용'),
    sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='조회수'),
    sa.Column('is_answered', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='답변 완료 여부'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='소프트 삭제 여부'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='삭제 일시'),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True, comment='삭제한 사용자 ID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='작성일시'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='course_questions_course_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='course_questions_deleted_by_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='course_questions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='course_questions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_course_questions_user_id'), 'course_questions', ['user_id'], unique=False)
    op.create_index(op.f('ix_course_questions_course_id'), 'course_questions', ['course_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='댓글 고유 ID'),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='질문 ID'),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='작성자 ID'),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='부모 댓글 ID (대댓글용)'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='댓글 내용'),
    sa.Column('is_instructor_answer', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='강사 답변 여부'),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='소프트 삭제 여부'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='삭제 일시'),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True, comment='삭제한 사용자 ID'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='작성일시'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('comments_deleted_by_fkey')),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], name=op.f('comments_parent_id_fkey')),
    sa.ForeignKeyConstraint(['question_id'], ['course_questions.id'], name=op.f('comments_question_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('comments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_comments_question_id'), 'comments', ['question_id'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='수료증 고유 ID'),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='사용자 ID'),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='강의 ID'),
    sa.Column('enrollment_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='수강 등록 ID'),
    sa.Column('certificate_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='수료증 번호 (예: WNIV-2025-000001)'),
    sa.Column('issued_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='발급일시'),
    sa.Column('pdf_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='PDF 파일 URL'),
    sa.Column('pdf_generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='PDF 생성일시'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('certificates_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('certificates_enrollment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('certificates_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('certificates_pkey'))
    )
    op.create_index(op.f('ix_certificates_user_id'), 'certificates', ['user_id'], unique=False)
    op.create_index(op.f('ix_certificates_enrollment_id'), 'certificates', ['enrollment_id'], unique=True)
    op.create_index(op.f('ix_certificates_course_id'), 'certificates', ['course_id'], unique=False)
    op.create_index(op.f('ix_certificates_certificate_number'), 'certificates', ['certificate_number'], unique=True)
    op.create_table('missions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('missions_id_seq'::regclass)"), autoincrement=True, nullable=False, comment='미션 고유 ID'),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='강의 ID'),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='미션 제목'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False, comment='미션 설명'),
    sa.Column('mission_type', postgresql.ENUM('midterm', 'final', name='missiontype'), autoincrement=False, nullable=False, comment='미션 유형'),
    sa.Column('question_type', postgresql.ENUM('multiple_choice', 'code', name='questiontype'), autoincrement=False, nullable=False, comment='문제 유형'),
    sa.Column('question_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='문제 데이터 (JSON 형태)'),
    sa.Column('answer_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='정답 데이터 (JSON 형태)'),
    sa.Column('max_score', sa.INTEGER(), autoincrement=False, nullable=False, comment='최대 점수'),
    sa.Column('passing_score', sa.INTEGER(), autoincrement=False, nullable=False, comment='통과 기준 점수'),
    sa.Column('max_attempts', sa.INTEGER(), autoincrement=False, nullable=False, comment='최대 제출 횟수'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='생성일시'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='missions_course_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='missions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_missions_course_id'), 'missions', ['course_id'], unique=False)
    op.create_table('mission_submissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='제출 고유 ID'),
    sa.Column('mission_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='미션 ID'),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='사용자 ID'),
    sa.Column('answer', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='제출 답안 (JSON 형태)'),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False, comment='획득 점수'),
    sa.Column('is_passed', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='통과 여부'),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True, comment='피드백'),
    sa.Column('execution_result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='실행 결과 (코드 제출형, JSON 형태)'),
    sa.Column('attempt_number', sa.INTEGER(), autoincrement=False, nullable=False, comment='시도 횟수'),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='제출일시'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], name=op.f('mission_submissions_mission_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('mission_submissions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mission_submissions_pkey'))
    )
    op.create_index(op.f('ix_mission_submissions_user_id'), 'mission_submissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_mission_submissions_mission_id'), 'mission_submissions', ['mission_id'], unique=False)
    # ### end Alembic commands ###
