"""add enrollment_id to progress model

Revision ID: 3605e891aa35
Revises: cded05cdf993
Create Date: 2025-11-14 15:04:51.942561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3605e891aa35'
down_revision: Union[str, Sequence[str], None] = 'cded05cdf993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('progresses', sa.Column('enrollment_id', sa.Integer(), nullable=True, comment='수강 등록 ID'))

    # Populate enrollment_id from existing data
    # Join progresses with lectures, chapters, and enrollments to find matching enrollment_id
    op.execute("""
        UPDATE progresses p
        SET enrollment_id = e.id
        FROM enrollments e, lectures l, chapters ch
        WHERE p.lecture_id = l.id
        AND l.chapter_id = ch.id
        AND ch.course_id = e.course_id
        AND p.user_id = e.user_id
    """)

    # Make column non-nullable
    op.alter_column('progresses', 'enrollment_id', nullable=False)

    op.create_index(op.f('ix_progresses_enrollment_id'), 'progresses', ['enrollment_id'], unique=False)
    op.create_foreign_key(None, 'progresses', 'enrollments', ['enrollment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'progresses', type_='foreignkey')
    op.drop_index(op.f('ix_progresses_enrollment_id'), table_name='progresses')
    op.drop_column('progresses', 'enrollment_id')
    # ### end Alembic commands ###
