"""get course and courses

Revision ID: 57a22e24f927
Revises: 2b19a37696b1
Create Date: 2025-11-14 12:31:07.966779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a22e24f927'
down_revision: Union[str, Sequence[str], None] = '2b19a37696b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('instructor_description', sa.Text(), nullable=True, comment='강사 상세 설명'))
    op.add_column('courses', sa.Column('access_duration_days', sa.Integer(), nullable=True, comment='수강 기한 (일 수, 예: 365)'))
    op.add_column('courses', sa.Column('max_students', sa.Integer(), nullable=True, comment='모집 인원'))
    op.add_column('courses', sa.Column('recruitment_start_date', sa.DateTime(), nullable=True, comment='모집 시작일'))
    op.add_column('courses', sa.Column('recruitment_end_date', sa.DateTime(), nullable=True, comment='모집 종료일'))
    op.add_column('courses', sa.Column('course_start_date', sa.DateTime(), nullable=True, comment='교육 시작일'))
    op.add_column('courses', sa.Column('course_end_date', sa.DateTime(), nullable=True, comment='교육 종료일'))
    op.add_column('courses', sa.Column('student_reviews', sa.Text(), nullable=True, comment='수강생 후기 (JSON 형태 또는 텍스트)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'student_reviews')
    op.drop_column('courses', 'course_end_date')
    op.drop_column('courses', 'course_start_date')
    op.drop_column('courses', 'recruitment_end_date')
    op.drop_column('courses', 'recruitment_start_date')
    op.drop_column('courses', 'max_students')
    op.drop_column('courses', 'access_duration_days')
    op.drop_column('courses', 'instructor_description')
    # ### end Alembic commands ###
