"""make course images nullable

Revision ID: 9c280b065c24
Revises: 7c1a4de1de38
Create Date: 2025-12-11 17:10:22.655391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c280b065c24'
down_revision: Union[str, Sequence[str], None] = '7c1a4de1de38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'thumbnail_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True,
               existing_comment='썸네일 이미지 URL')
    op.alter_column('courses', 'instructor_image',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_comment='강사 프로필 이미지 URL')
    op.alter_column('progresses', 'watched_seconds',
               existing_type=sa.INTEGER(),
               comment='총 시청 시간 (초) - 반복 재생 포함 누적',
               existing_comment='총 시청 시간 (초)',
               existing_nullable=False)
    op.alter_column('progresses', 'unique_watched_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='최대 도달 위치 (초) - 진행률 계산용, 되감기 시에도 감소하지 않음',
               existing_comment='유니크 시청 시간 (초) - 진행률 계산용',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('progresses', 'unique_watched_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='유니크 시청 시간 (초) - 진행률 계산용',
               existing_comment='최대 도달 위치 (초) - 진행률 계산용, 되감기 시에도 감소하지 않음',
               existing_nullable=False)
    op.alter_column('progresses', 'watched_seconds',
               existing_type=sa.INTEGER(),
               comment='총 시청 시간 (초)',
               existing_comment='총 시청 시간 (초) - 반복 재생 포함 누적',
               existing_nullable=False)
    op.alter_column('courses', 'instructor_image',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_comment='강사 프로필 이미지 URL')
    op.alter_column('courses', 'thumbnail_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False,
               existing_comment='썸네일 이미지 URL')
    # ### end Alembic commands ###
