"""user 및 course 스키마와 모델 변경 (강의목록 조회와 회원가입 필수입력값 변경)

Revision ID: ace990837f3d
Revises: 7c54060c947b
Create Date: 2025-11-13 12:13:51.738754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ace990837f3d'
down_revision: Union[str, Sequence[str], None] = '7c54060c947b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'other', name='gender'),
               nullable=True,
               existing_comment='성별')
    op.alter_column('users', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_comment='생년월일')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_comment='생년월일')
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'other', name='gender'),
               nullable=False,
               existing_comment='성별')
    # ### end Alembic commands ###
