"""initial_fresh_migration

Revision ID: af80c455bfd2
Revises: 
Create Date: 2025-11-14 18:04:34.538216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af80c455bfd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='강의 고유 ID'),
    sa.Column('category_type', sa.Enum('frontend', 'backend', 'data_analysis', 'ai', 'design', 'other', name='categorytype'), nullable=False, comment='카테고리 유형'),
    sa.Column('course_type', sa.Enum('vod', 'boost_community', 'kdc', name='coursetype'), nullable=False, comment='강의 유형'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='강의 제목'),
    sa.Column('description', sa.Text(), nullable=False, comment='강의 설명'),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=False, comment='썸네일 이미지 URL'),
    sa.Column('instructor_name', sa.String(length=100), nullable=False, comment='강사명'),
    sa.Column('instructor_bio', sa.Text(), nullable=False, comment='강사 소개'),
    sa.Column('instructor_description', sa.Text(), nullable=True, comment='강사 상세 설명'),
    sa.Column('instructor_image', sa.String(length=500), nullable=False, comment='강사 프로필 이미지 URL'),
    sa.Column('difficulty', sa.Enum('beginner', 'intermediate', 'advanced', name='difficulty'), nullable=False, comment='난이도'),
    sa.Column('price_type', sa.Enum('free', 'paid', 'national_support', name='pricetype'), nullable=False, comment='가격 유형'),
    sa.Column('price', sa.Integer(), nullable=False, comment='실제 가격 (원)'),
    sa.Column('total_duration', sa.Integer(), nullable=False, comment='전체 강의 시간 (초)'),
    sa.Column('access_duration_days', sa.Integer(), nullable=True, comment='수강 기한 (일 수, 예: 365)'),
    sa.Column('max_students', sa.Integer(), nullable=True, comment='모집 인원'),
    sa.Column('recruitment_start_date', sa.DateTime(), nullable=True, comment='모집 시작일'),
    sa.Column('recruitment_end_date', sa.DateTime(), nullable=True, comment='모집 종료일'),
    sa.Column('course_start_date', sa.DateTime(), nullable=True, comment='교육 시작일'),
    sa.Column('course_end_date', sa.DateTime(), nullable=True, comment='교육 종료일'),
    sa.Column('student_reviews', sa.Text(), nullable=True, comment='수강생 후기 (JSON 형태 또는 텍스트)'),
    sa.Column('faq', sa.Text(), nullable=True, comment='자주 묻는 질문 (JSON 형태)'),
    sa.Column('is_published', sa.Boolean(), nullable=False, comment='공개 여부'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_title'), 'courses', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='사용자 고유 ID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='비밀번호 해시 (소셜 로그인 시 NULL)'),
    sa.Column('nickname', sa.String(length=18), nullable=False, comment='닉네임 (2~18자)'),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=True, comment='성별'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='생년월일'),
    sa.Column('profile_image', sa.String(length=500), nullable=True, comment='프로필 이미지 URL'),
    sa.Column('role', sa.Enum('student', 'admin', name='userrole'), nullable=False, comment='사용자 역할'),
    sa.Column('social_provider', sa.Enum('email', 'google', 'github', name='socialprovider'), nullable=False, comment='소셜 로그인 제공자'),
    sa.Column('social_id', sa.String(length=255), nullable=True, comment='소셜 로그인 고유 ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='계정 활성화 여부'),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False, comment='이메일 인증 여부'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='가입일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='마지막 로그인 일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='챕터 고유 ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='강의 ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='챕터 제목'),
    sa.Column('description', sa.Text(), nullable=True, comment='챕터 설명'),
    sa.Column('order_number', sa.Integer(), nullable=False, comment='챕터 순서'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_course_id'), 'chapters', ['course_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='수강 등록 고유 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='강의 ID'),
    sa.Column('enrolled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='등록일시'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='만료일시 (등록일 + 2년)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('progress_rate', sa.Float(), nullable=False, comment='전체 진행률 0~100'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='결제 고유 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('course_id', sa.Integer(), nullable=False, comment='강의 ID'),
    sa.Column('coupon_id', sa.Integer(), nullable=True, comment='쿠폰 ID (미사용)'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='원래 가격'),
    sa.Column('discount_amount', sa.Integer(), nullable=False, comment='할인 금액'),
    sa.Column('final_amount', sa.Integer(), nullable=False, comment='최종 결제 금액'),
    sa.Column('payment_method', sa.Enum('card', 'transfer', 'toss', name='paymentmethod'), nullable=False, comment='결제 방식'),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded', name='paymentstatus'), nullable=False, comment='결제 상태'),
    sa.Column('transaction_id', sa.String(length=100), nullable=True, comment='PG사 거래 ID'),
    sa.Column('receipt_url', sa.String(length=500), nullable=True, comment='영수증 URL'),
    sa.Column('paid_at', sa.DateTime(), nullable=True, comment='실제 결제 완료 시각'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_course_id'), 'payments', ['course_id'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('lectures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='강의 영상 고유 ID'),
    sa.Column('chapter_id', sa.Integer(), nullable=False, comment='챕터 ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='강의 제목'),
    sa.Column('description', sa.Text(), nullable=True, comment='강의 설명'),
    sa.Column('video_url', sa.String(length=500), nullable=False, comment='동영상 URL'),
    sa.Column('video_type', sa.Enum('vod', 'youtube', name='videotype'), nullable=False, comment='동영상 타입'),
    sa.Column('duration_seconds', sa.Integer(), nullable=False, comment='재생 시간 (초)'),
    sa.Column('order_number', sa.Integer(), nullable=False, comment='강의 순서'),
    sa.Column('material_url', sa.String(length=500), nullable=True, comment='강의 자료 URL'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lectures_chapter_id'), 'lectures', ['chapter_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='환불 고유 ID'),
    sa.Column('payment_id', sa.Integer(), nullable=False, comment='결제 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='환불 금액'),
    sa.Column('reason', sa.Text(), nullable=False, comment='환불 사유'),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='refundstatus'), nullable=False, comment='환불 상태'),
    sa.Column('admin_note', sa.Text(), nullable=True, comment='관리자 메모'),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='요청일시'),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='처리 완료 시각'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=True)
    op.create_index(op.f('ix_refunds_user_id'), 'refunds', ['user_id'], unique=False)
    op.create_table('progresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='진행 상황 고유 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('enrollment_id', sa.Integer(), nullable=False, comment='수강 등록 ID'),
    sa.Column('lecture_id', sa.Integer(), nullable=False, comment='강의 ID'),
    sa.Column('watched_seconds', sa.Integer(), nullable=False, comment='총 시청 시간 (초)'),
    sa.Column('last_position', sa.Integer(), nullable=False, comment='마지막 시청 위치 (초)'),
    sa.Column('is_completed', sa.Boolean(), nullable=False, comment='완료 여부'),
    sa.Column('last_watched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='마지막 시청 일시'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='완료 일시'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progresses_enrollment_id'), 'progresses', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_progresses_lecture_id'), 'progresses', ['lecture_id'], unique=False)
    op.create_index(op.f('ix_progresses_user_id'), 'progresses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progresses_user_id'), table_name='progresses')
    op.drop_index(op.f('ix_progresses_lecture_id'), table_name='progresses')
    op.drop_index(op.f('ix_progresses_enrollment_id'), table_name='progresses')
    op.drop_table('progresses')
    op.drop_index(op.f('ix_refunds_user_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_lectures_chapter_id'), table_name='lectures')
    op.drop_table('lectures')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_course_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_chapters_course_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_courses_title'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
