"""delete some models and schemas

Revision ID: cded05cdf993
Revises: 297948e996b1
Create Date: 2025-11-14 14:56:58.361937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cded05cdf993'
down_revision: Union[str, Sequence[str], None] = '297948e996b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 먼저 외래 키 제약 조건을 제거
    op.drop_constraint(op.f('payments_coupon_id_fkey'), 'payments', type_='foreignkey')

    # 컬럼 코멘트 변경
    op.alter_column('payments', 'coupon_id',
               existing_type=sa.INTEGER(),
               comment='쿠폰 ID (미사용)',
               existing_comment='쿠폰 ID',
               existing_nullable=True)

    # 그 다음 인덱스와 테이블 삭제
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('payments_coupon_id_fkey'), 'payments', 'coupons', ['coupon_id'], ['id'])
    op.alter_column('payments', 'coupon_id',
               existing_type=sa.INTEGER(),
               comment='쿠폰 ID',
               existing_comment='쿠폰 ID (미사용)',
               existing_nullable=True)
    op.create_table('coupons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='쿠폰 고유 ID'),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='강의 ID (NULL이면 전체 강의)'),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='쿠폰 코드'),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='쿠폰 이름'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False, comment='쿠폰 설명'),
    sa.Column('discount_rate', sa.INTEGER(), autoincrement=False, nullable=True, comment='할인율 (%)'),
    sa.Column('discount_amount', sa.INTEGER(), autoincrement=False, nullable=True, comment='할인 금액 (원)'),
    sa.Column('valid_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='유효 시작일'),
    sa.Column('valid_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='유효 종료일'),
    sa.Column('max_usage', sa.INTEGER(), autoincrement=False, nullable=False, comment='최대 사용 인원 (0이면 무제한)'),
    sa.Column('used_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='사용된 인원 수'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='활성화 여부'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='생성일시'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('coupons_course_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('coupons_pkey'))
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    # ### end Alembic commands ###
