"""
BootRun Schemas Package
모든 Pydantic 스키마를 중앙에서 관리

순환 참조 방지를 위해 의존성 순서대로 import:
1. common (독립적)
2. user (common 의존)
3. course (common 의존)
4. enrollment (user, course 의존)
5. mission (course 의존)
6. payment (user, course 의존)
7. certificate (user, course, enrollment 의존)
8. admin (모든 모듈 의존)
"""

# ============= Common schemas (최우선) =============
from .common import (
    PaginationParams,
    PaginatedResponse,
    MessageResponse,
    ErrorResponse,
    DateRangeFilter,
    FileUploadResponse,
    ImageUploadResponse,
)

# ============= User schemas =============
from .user import (
    UserCreate,
    UserLogin,
    UserUpdate,
    UserResponse,
    UserListResponse,
    TokenResponse,
    EmailVerificationRequest,
    EmailVerificationConfirm,
    SocialLoginRequest,
    PasswordResetRequest,
    PasswordResetConfirm,
    UserDeleteRequest,
    UserRole,
    Gender,
    SocialProvider,
)

# ============= Course schemas =============
from .course import (
    CategoryResponse,
    CategoryCreate,
    CategoryUpdate,
    CourseCreate,
    CourseUpdate,
    CourseResponse,
    CourseDetailResponse,
    CourseListParams,
    CoursePaginatedResponse,
    ChapterCreate,
    ChapterUpdate,
    ChapterResponse,
    ChapterWithLectures,
    LectureCreate,
    LectureUpdate,
    LectureResponse,
    QuestionCreate,
    QuestionUpdate,
    QuestionResponse,
    QuestionDetailResponse,
    QuestionListParams,
    CommentCreate,
    CommentUpdate,
    CommentResponse,
    CommentSummary,
    CategoryType,
    Difficulty,
    VideoType,
)

# ============= Enrollment schemas =============
from .enrollment import (
    EnrollmentCreate,
    EnrollmentResponse,
    EnrollmentDetailResponse,
    EnrollmentPaginatedResponse,
    MyEnrollmentListParams,
    ProgressCreate,
    ProgressUpdate,
    ProgressResponse,
    LectureProgressSummary,
    ChapterProgressSummary,
    CourseProgressDetail,
    StudentDashboard,
    LearningStats,
)

# ============= Mission schemas =============
from .mission import (
    MissionCreate,
    MissionUpdate,
    MissionResponse,
    MissionWithUserStatus,
    MissionSubmissionCreate,
    MissionSubmissionResponse,
    MissionSubmissionHistory,
    UserMissionProgress,
    CodeExecutionRequest,
    CodeExecutionResponse,
    MissionStats,
    MissionType,
    QuestionType,
)

# ============= Payment schemas =============
from .payment import (
    PaymentCreate,
    PaymentResponse,
    PaymentDetailResponse,
    PaymentPaginatedResponse,
    PaymentListParams,
    CouponCreate,
    CouponUpdate,
    CouponResponse,
    CouponValidationRequest,
    CouponValidationResponse,
    RefundCreate,
    RefundUpdate,
    RefundResponse,
    RefundListParams,
    RefundCheckResponse,
    PaymentMethod,
    PaymentStatus,
    RefundStatus,
)

# ============= Certificate schemas =============
from .certificate import (
    CertificateCreate,
    CertificateResponse,
    CertificateListResponse,
    CertificateGenerationRequest,
    CertificateGenerationResponse,
    CertificateVerifyRequest,
    CertificateVerifyResponse,
    CertificateVerifyDetail,
    CompletionCheckRequest,
    CompletionCheckResponse,
    CompletionRequirement,
)

# ============= Admin schemas (최후순위) =============
from .admin import (
    DashboardStats,
    DailyStats,
    RevenueStats,
    CourseStats,
    CategoryStats,
    UserManagementListParams,
    UserManagementResponse,
    UserManagementPaginatedResponse,
    UserDetailForAdmin,
    UserLearningRecord,
    UserAttendanceRecord,
    UserProgressDetail,
    UserLearningReport,
    CourseManagementListParams,
    CourseManagementResponse,
    CourseManagementPaginatedResponse,
    PaymentManagementListParams,
    PaymentManagementResponse,
    PaymentManagementPaginatedResponse,
    RefundManagementListParams,
    RefundManagementResponse,
    RefundManagementPaginatedResponse,
    StatsQueryParams,
    CourseStatsQueryParams,
    SystemSettings,
    StatsPeriod,
)

# ============= Public API 명시 =============
__all__ = [
    # Common
    "PaginationParams",
    "PaginatedResponse",
    "MessageResponse",
    "ErrorResponse",
    "DateRangeFilter",
    "FileUploadResponse",
    "ImageUploadResponse",
    # User
    "UserCreate",
    "UserLogin",
    "UserUpdate",
    "UserResponse",
    "UserListResponse",
    "TokenResponse",
    "EmailVerificationRequest",
    "EmailVerificationConfirm",
    "SocialLoginRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "UserDeleteRequest",
    "UserRole",
    "Gender",
    "SocialProvider",
    # Course
    "CategoryResponse",
    "CategoryCreate",
    "CategoryUpdate",
    "CourseCreate",
    "CourseUpdate",
    "CourseResponse",
    "CourseDetailResponse",
    "CourseListParams",
    "CoursePaginatedResponse",
    "ChapterCreate",
    "ChapterUpdate",
    "ChapterResponse",
    "ChapterWithLectures",
    "LectureCreate",
    "LectureUpdate",
    "LectureResponse",
    "QuestionCreate",
    "QuestionUpdate",
    "QuestionResponse",
    "QuestionDetailResponse",
    "QuestionListParams",
    "CommentCreate",
    "CommentUpdate",
    "CommentResponse",
    "CommentSummary",
    "CategoryType",
    "Difficulty",
    "VideoType",
    # Enrollment
    "EnrollmentCreate",
    "EnrollmentResponse",
    "EnrollmentDetailResponse",
    "EnrollmentPaginatedResponse",
    "MyEnrollmentListParams",
    "ProgressCreate",
    "ProgressUpdate",
    "ProgressResponse",
    "LectureProgressSummary",
    "ChapterProgressSummary",
    "CourseProgressDetail",
    "StudentDashboard",
    "LearningStats",
    # Mission
    "MissionCreate",
    "MissionUpdate",
    "MissionResponse",
    "MissionWithUserStatus",
    "MissionSubmissionCreate",
    "MissionSubmissionResponse",
    "MissionSubmissionHistory",
    "UserMissionProgress",
    "CodeExecutionRequest",
    "CodeExecutionResponse",
    "MissionStats",
    "MissionType",
    "QuestionType",
    # Payment
    "PaymentCreate",
    "PaymentResponse",
    "PaymentDetailResponse",
    "PaymentPaginatedResponse",
    "PaymentListParams",
    "CouponCreate",
    "CouponUpdate",
    "CouponResponse",
    "CouponValidationRequest",
    "CouponValidationResponse",
    "RefundCreate",
    "RefundUpdate",
    "RefundResponse",
    "RefundListParams",
    "RefundCheckResponse",
    "PaymentMethod",
    "PaymentStatus",
    "RefundStatus",
    # Certificate
    "CertificateCreate",
    "CertificateResponse",
    "CertificateListResponse",
    "CertificateGenerationRequest",
    "CertificateGenerationResponse",
    "CertificateVerifyRequest",
    "CertificateVerifyResponse",
    "CertificateVerifyDetail",
    "CompletionCheckRequest",
    "CompletionCheckResponse",
    "CompletionRequirement",
    # Admin
    "DashboardStats",
    "DailyStats",
    "RevenueStats",
    "CourseStats",
    "CategoryStats",
    "UserManagementListParams",
    "UserManagementResponse",
    "UserManagementPaginatedResponse",
    "UserDetailForAdmin",
    "UserLearningRecord",
    "UserAttendanceRecord",
    "UserProgressDetail",
    "UserLearningReport",
    "CourseManagementListParams",
    "CourseManagementResponse",
    "CourseManagementPaginatedResponse",
    "PaymentManagementListParams",
    "PaymentManagementResponse",
    "PaymentManagementPaginatedResponse",
    "RefundManagementListParams",
    "RefundManagementResponse",
    "RefundManagementPaginatedResponse",
    "StatsQueryParams",
    "CourseStatsQueryParams",
    "SystemSettings",
    "StatsPeriod",
]